# Generated by Django 4.1.6 on 2023-02-05 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='type',
            new_name='gender',
        ),
    ]
