# Generated by Django 4.1.6 on 2023-02-05 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountaddress',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='account.city'),
        ),
    ]
