# Generated by Django 4.1.6 on 2023-02-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='discount', max_length=100)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'قیمتی'), (2, 'درصدی')])),
                ('amount', models.IntegerField()),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'فعال'), (2, 'غیرفعال')])),
                ('discount_limit', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ManyToManyField(to='product.discount'),
        ),
    ]
